### ISSUE TITLE
Twig 3 incompatibility

### ISSUE THREAD

**Issue by garak** [bearlikelion/twig-jsontools#3]
Declared compatibility with Twig is too lax: this lib is not compatible with Twig 3.
You should:
1) declare explicit compatibility with Twig 1 and Twig 2
2) tag a new minor release
3) change compatibility to work with Twig 3
4) tag a new major release

I can provide a PR.

**Comment by bearlikelion** [comment]
I would greatly appreciate a PR for this

**Comment by garak** [comment]
remember that you should publish mentioned releases

**Comment by bearlikelion** [comment]
Thank you
